version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      PGADMIN_CONFIG_SERVER_MODE: "False"
  keycloak:
    build: ./keycloak
    depends_on:
      - postgres
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      DB_SCHEMA: public
      KEYCLOAK_IMPORT: /tmp/tindeer-realm.json
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - 8080:8080
  pgadmin:
    build: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: keycloak@tindeer.com
      PGADMIN_DEFAULT_PASSWORD: keycloak
    ports:
      - 5050:80
    depends_on:
      - postgres  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  profile:
    image: tindeer/brinder-profile-api
    ports:
      - 9080:8080
    environment:
      spring_profiles_active: security,docker
    depends_on:
      - mongo
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /doc/tindeer.yaml
      DEEP_LINKING: "true"
      OAUTH2_REDIRECT_URL: http://localhost:8888/oauth2-redirect.html
      OAUTH_CLIENT_ID: swagger
      OAUTH_USE_PKCE: "true"  
      OAUTH_REALM: tindeer
      OAUTH_APP_NAME: swagger
    ports: 
      - 8888:8080
    volumes:
      - ./swagger:/doc