spring:
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/tindeer
logging:
  level:
    org:
      springframework:
        security: debug